application: svvfd-callout
version: 1
module: webcron
runtime: php55
api_version: 1

handlers:
- url: /riprunner
  script: riprunner-trigger.php
  login: admin

- url: /.*
  script: riprunner-trigger.php
  login: admin
    